# Makefile

build:
	./gradlew clean build

clean:
	./gradlew clean

run:
	./gradlew run

test:
	./gradlew test

lint:
	./gradlew checkstyleMain

install:
	./gradlew installDist

lint:
	./gradlew checkstyleMain

.PHONY: build
.PHONY: test