name: project-72-check
run-name: ${{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5
          arguments: build --scan
          build-root-directory: app
